### ISSUE TITLE
Histou installation

### ISSUE THREAD

**Issue by dpeer77** [Griesbacher/histou#2]
Hello,

I install histou along with nagflux but I have troubles to get it working and I might miss something.
I have nagios complied and installed under /usr/local/nagios. histou installed under 
/usr/local/nagios/share/histou and I copied histou.js under grafana /usr/share/grafana/public/dashboards/histou.js. How can I get Histou working meaning showing me perf data like PNP4nagios?
grafana URL for my installation is: http://{server-ip}:3000 and nagios is under http://{server-ip}
I'm new to grafana/influxdb.

Doess someone knows how to configure that?

Thanks,
David

**Comment by Griesbacher** [comment]
Hi David,

take a look at OMD Labs, it might be easier to get running there.
Here is a instruction how to activate everything: https://labs.consol.de/de/nagios/omd/2015/10/21/activate-nagflux.html
There is also a Dockerimage which may help you out, it contains OMD with everything pre configured: https://github.com/Griesbacher/docker-omd-grafana

Greetings,
Philip

**Comment by dpeer77** [comment]
Philip, great! it works for me now perfectly and I can tell your work is really awesome/helpful.
great project and sharing.

**Comment by dtypos** [comment]
Hi. I am trying to integrate Nagios Core with Grafana, with influxdb as found in https://support.nagios.com/kb/article/nagios-core-4-status-maps-681.html and https://www.youtube.com/watch?v=8OCfIVdfqqE&t=912s. Everything works fine, except Histou which from curl -G -vvv "http://localhost/histou/?host=localhost&service=PING" --ipv4 reports an " HTTP/1.1 500 Internal Server Error".

Is there anyway to check the Histou functionality (logs or load)? Is there any workaround?
[ My env: Rocky Linux 9.4 | Nagios Core 4.5.9 | influxdb-1.11.8 | grafana-11.5.1 ]
