### ISSUE TITLE
Remote InfluxDB

### ISSUE THREAD

**Issue by jframeau** [Griesbacher/histou#3]
Hi,

I managed to install a Thruk/Naemon monitoring station with influxdb/grafana on a remote host because of IO considerations.

Thanks to nagflux, performance data are stored into remote influxdb but I didn't find the right way to configure histou for Thruk with such an architecture.

First, I tried to install histou onto the monitoring station. histou.js has been published to grafana dashboard directory but Thruk doesn't display graphs.

Second, I tried to install histou on influxdb/grafana station, but without success too.

Finally, I wonder if remoting influxdb/grafana is likely to work today ?

jfr

**Comment by sni** [comment]
it definitly works. You could try a reverse proxy from the apache maybe.

**Comment by jframeau** [comment]
Good news.
But where did you install histou ? On the Thruk/Naemon side or on InfluxDB/Grafana side ?

I think on InfluxDB/Grafana side is better if I understand well.

Thruk needs to display a graph -> call to grafana/histou.js -> call to /histou -> call to influxdb

So I think histou and influxdb should be on the same side to minimize network accesses.

Am I right ?

**Comment by Griesbacher** [comment]
That should be fine, so you have all the graphing stuff on one machine.

Your callgraph is correct.

**Comment by Griesbacher** [comment]
I'll close that one due to inactivity.
