### ISSUE TITLE
generate bitmap images

### ISSUE THREAD

**Issue by uplink** [Griesbacher/histou#35]
I happily started using Histou (replacing pnp4nagios due to incompatibility to current PHP versions).
What I did before, was to have a simple "dashboard" (i.e. a HTML page) displayed by some raspi-driven monitor that showed the top 5 issues together with a performance graph of the last few days. This was easy with pnp4nagios, as pngs were generated by default, which the raspi could show without much need for computation.

Now, after having switched to Histou/Grafana for my naemon performance graphing needs (great stuff btw), I cannot do this anymore, as I need to include a large JS driven website as iframe for each of my 5 top alerts. The Raspi simply cannot render this in time for the next refresh (30s).

So, I am looking for a way to have some component generate svg/png/… instead.
 
Is there such functionality that I missed in my searches? Or are there plans in histou for this?

Thanks for any thoughts on this.

P.S.: thanks @Griesbacher for histou

**Comment by jacobbaungard** [comment]
Grafana does support getting an image as a png, you can use something like:

http://localhost:3000/render/dashboard-solo/script/histou.js?host=hostname...

**Comment by uplink** [comment]
Thanks @jacobbaungard ,I missed that. Works great!
