### ISSUE TITLE
Support for Last, Max and Average

### ISSUE THREAD

**Issue by jstark1** [Griesbacher/histou#39]
is there a way to display the Last, Max and Average values like pnp does?

**Comment by sni** [comment]
Same as in #40, Histou basically has nothing to do with pnp and is just a template engine to generate grafana graphs.

**Comment by dan-m-joh** [comment]
See
```
setLegend(
show = SHOW_LEGEND,
values = false,
min = false,
max = false,
current = false,
total = false,
avg = false,
alignAsTable = false,
rightSide = false,
hideEmpty = true
)
```

**Comment by jstark1** [comment]
setLegend works perfect, thanks
