### ISSUE TITLE
How to view histou graphs in grafana

### ISSUE THREAD

**Issue by scott-fed** [Griesbacher/histou#7]
Hello,

I just installed the OMD 2.20 labs edition today. I was trying to get data graphed in grafana and found that histou has templates to make it a bit easier. For some reason, I can not see these templates in grafana. I have read https://labs.consol.de/de/nagios/omd/2015/10/21/activate-nagflux.html and still I am unable to view them in grafana. I've also searched google for hours an I can't figure it out. I'm running this on SLES 11 SP3.

**Comment by Griesbacher** [comment]
You'll never see them in Grafana like you see your own dashboards. They are created just once and designed to be dynamic and not statical like normal Grafana dashboards. Have a look at this demo system: https://demo.thruk.org/thruk/cgi-bin/extinfo.cgi?type=2&host=icinga2&service=disk%20%2F&backend=cacb0#histou_th2/1480775405/1480865405/1 
You can click on the graphpreview or action url to get directed to grafana. It's maybe easier to see it, then to explain in short.

**Comment by scott-fed** [comment]
Thanks for the explanation, Philip.

**Comment by Griesbacher** [comment]
You probably didn't update the actionurl or you didn't just click on the action icon.

It is possible to save all the generated dashboards in Grafana, and we tried that once to save them just to test Grafana, if you have a decent environment, Grafana won't make it ;)

Hope that helps.
Greetings,
Philip

**Comment by scott-fed** [comment]
I'm also using check_mk instead of thurk to configure and view host details. So I guess that is also why I didn't see the action icons which I saw in your thurk demo.

**Comment by Griesbacher** [comment]
That's true, at least I'm not aware of any integration of Histou in check_mk. like Thruk has. But therefore the check_mk guys are the ones which have to add the support in their webpage.

**Comment by scott-fed** [comment]
Unfortunately OMD labs documentation didn't point this out. I appreciate your prompt responses. Thanks!

**Comment by Griesbacher** [comment]
Your welcome
