### ISSUE TITLE
Empty graphs or no data points

### ISSUE THREAD

**Issue by dpeer77** [Griesbacher/histou#9]
Hi,

I have installed the Histou latest along with Grafana 4.1.1-1484211277 and Influxdb 1.1.1-1, on Ubuntu 14.04.
In the generated graphs/templates I see no data, but when I edit the graph and go to "Display"->"Stacking & Null value", and change the "Null value" from "null" to "connected", I do see the data.
What can I do/change in order to set that as a default behavior of Histou or Grafana? I tried to look for it a little on the web and in the code, but could not find it.

Thanks,
David

**Comment by Griesbacher** [comment]
Hi David,

thanks for the issue, could you try this fix on your system? I think it should solve the problem.
If so, I'll make a new release and also add it to OMD.

Greetings,
Philip
